apiVersion: apps/v1
kind: Deployment
metadata:
  name: onlinebookstore
spec:
  replicas: 2
  selector:
    matchLabels:
      app: onlinebookstore
  template:
    metadata:
      labels:
        app: onlinebookstore
    spec:
      containers:
        - name: onlinebookstore
          image: 481665090399.dkr.ecr.us-east-1.amazonaws.com/demo:latest
          ports:
          - containerPort: 8080
